definitions:
  main.FlooringMatchesResponse:
    properties:
      partners:
        items:
          $ref: '#/definitions/main.Partner'
        type: array
    type: object
  main.Partner:
    properties:
      addressLat:
        type: number
      addressLon:
        type: number
      distance:
        type: number
      id:
        type: integer
      operatingRadius:
        type: number
      rating:
        type: number
      services:
        items:
          $ref: '#/definitions/main.Service'
        type: array
    type: object
  main.QueryParams:
    properties:
      address_lat:
        type: number
      address_lon:
        type: number
      floor_size:
        type: number
      phone_number:
        type: string
      services:
        items:
          type: string
        type: array
    required:
    - address_lat
    - address_lon
    - floor_size
    - phone_number
    - services
    type: object
  main.Service:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /matches/flooring:
    post:
      consumes:
      - application/json
      description: Retrieves matches based on flooring preferences submitted by the
        customer
      parameters:
      - description: Query Parameters
        in: body
        name: query
        required: true
        schema:
          $ref: '#/definitions/main.QueryParams'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/main.FlooringMatchesResponse'
        "400":
          description: bad request, invalid input
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Retrieve flooring matches
      tags:
      - matches
swagger: "2.0"
